# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vinmayp\Desktop\BILayer\VioletTheme\Aggregation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 550)
        Dialog.setStyleSheet("background-color: rgb(42, 38, 62);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    }")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    }")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 7)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.widget_2)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    }")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.listWidget_2 = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_2.setStyleSheet("QListWidget{\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    }")
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout.addWidget(self.listWidget_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    /*background-image: url(:/whiteIcons/featherwhite/calendar.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;*/\n"
"    background-color:rgb(99, 89, 145);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    width:60;\n"
"    height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    /*background-image: url(:/whiteIcons/featherwhite/calendar.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;*/\n"
"    background-color:rgb(99, 89, 145);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    width:60;\n"
"    height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Aggregation"))
        self.label_2.setText(_translate("Dialog", "Columns"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.pushButton.setText(_translate("Dialog", "OK"))
