# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vinmayp\Desktop\BILayer\BILayerFilterWOBTN.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(39, 39, 47);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(170, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/sidebar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton = QtWidgets.QPushButton(self.widget_8)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.widget_8)
        self.checkBox.setStyleSheet("color:white;")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toolBox = QtWidgets.QToolBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox{\n"
"    color:white;\n"
"    border-style: inset;\n"
"    border-width: 0px;\n"
"    border-color: rgb(170, 0, 255);\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style:none;\n"
"width:80px;\n"
"height:26px;\n"
"} \n"
"\n"
"QToolBox::tab:selected { \n"
"      background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(170, 0, 255);\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 177, 525))
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_14 = QtWidgets.QWidget(self.page)
        self.widget_14.setStyleSheet("color:white;")
        self.widget_14.setObjectName("widget_14")
        self.formLayout = QtWidgets.QFormLayout(self.widget_14)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setObjectName("formLayout")
        self.DBLabel = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DBLabel.sizePolicy().hasHeightForWidth())
        self.DBLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DBLabel.setFont(font)
        self.DBLabel.setStyleSheet("background-image: url(:/whiteIcons/featherwhite/database.svg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"color: rgb(55, 55, 64);")
        self.DBLabel.setObjectName("DBLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.DBLabel)
        self.DBComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DBComboBox.setFont(font)
        self.DBComboBox.setStyleSheet("QComboBox{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:23;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.DBComboBox.setObjectName("DBComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DBComboBox)
        self.SchemaLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SchemaLabel.setFont(font)
        self.SchemaLabel.setStyleSheet("background-image: url(:/whiteIcons/featherwhite/trello.svg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"color: rgb(55, 55, 64);")
        self.SchemaLabel.setObjectName("SchemaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.SchemaLabel)
        self.SchemaComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.SchemaComboBox.setFont(font)
        self.SchemaComboBox.setStyleSheet("QComboBox{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:23;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.SchemaComboBox.setObjectName("SchemaComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SchemaComboBox)
        self.TableLabel = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableLabel.sizePolicy().hasHeightForWidth())
        self.TableLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TableLabel.setFont(font)
        self.TableLabel.setStyleSheet("background-image: url(:/whiteIcons/featherwhite/table.svg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"color: rgb(55, 55, 64);")
        self.TableLabel.setObjectName("TableLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.TableLabel)
        self.TableComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.TableComboBox.setFont(font)
        self.TableComboBox.setStyleSheet("QComboBox{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:23;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.TableComboBox.setObjectName("TableComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.TableComboBox)
        self.TopRowsLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TopRowsLabel.setFont(font)
        self.TopRowsLabel.setStyleSheet("color: white;")
        self.TopRowsLabel.setObjectName("TopRowsLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.TopRowsLabel)
        self.TopRowsLineEdit = QtWidgets.QLineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopRowsLineEdit.sizePolicy().hasHeightForWidth())
        self.TopRowsLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TopRowsLineEdit.setFont(font)
        self.TopRowsLineEdit.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:80;\n"
"height:30;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"}")
        self.TopRowsLineEdit.setObjectName("TopRowsLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.TopRowsLineEdit)
        self.NullAsLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NullAsLabel.setFont(font)
        self.NullAsLabel.setStyleSheet("color: white;")
        self.NullAsLabel.setObjectName("NullAsLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.NullAsLabel)
        self.NullAsLineEdit = QtWidgets.QLineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NullAsLineEdit.sizePolicy().hasHeightForWidth())
        self.NullAsLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NullAsLineEdit.setFont(font)
        self.NullAsLineEdit.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:80;\n"
"height:30;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"}")
        self.NullAsLineEdit.setText("")
        self.NullAsLineEdit.setObjectName("NullAsLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.NullAsLineEdit)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 97, 134))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_15 = QtWidgets.QWidget(self.page_2)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.SearchSavedSqlLineEdit = QtWidgets.QLineEdit(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SearchSavedSqlLineEdit.setFont(font)
        self.SearchSavedSqlLineEdit.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:30;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"}")
        self.SearchSavedSqlLineEdit.setText("")
        self.SearchSavedSqlLineEdit.setObjectName("SearchSavedSqlLineEdit")
        self.verticalLayout_14.addWidget(self.SearchSavedSqlLineEdit)
        self.SavedSqlListWidget = QtWidgets.QListWidget(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SavedSqlListWidget.setFont(font)
        self.SavedSqlListWidget.setStyleSheet("")
        self.SavedSqlListWidget.setObjectName("SavedSqlListWidget")
        self.verticalLayout_14.addWidget(self.SavedSqlListWidget)
        self.verticalLayout_11.addWidget(self.widget_15)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_9.addWidget(self.toolBox)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_9)
        self.tabWidget.setStyleSheet("QTabWidget::pane { border: 0; }\n"
"\n"
"QTabWidget{\n"
"    border-style: none;\n"
"    border-width: 0px;\n"
"    border-color: rgb(170, 0, 255);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style:none;\n"
"width:80px;\n"
"height:26px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"      background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(170, 0, 255);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.Tool = QtWidgets.QWidget()
        self.Tool.setObjectName("Tool")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Tool)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.Tool)
        self.widget_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:30;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.listWidget = QtWidgets.QListWidget(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"height:40px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_4.addWidget(self.listWidget_2)
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 205, 627))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_17 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_17.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_17.setSpacing(2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_17.addWidget(self.label_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setAutoFillBackground(False)
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_17.addWidget(self.comboBox_5)
        self.verticalLayout_17.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_18.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_18.setSpacing(2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_18.addWidget(self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setAutoFillBackground(False)
        self.comboBox_6.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_18.addWidget(self.comboBox_6)
        self.verticalLayout_18.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_19.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_7 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_19.addWidget(self.label_7)
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setAutoFillBackground(False)
        self.comboBox_7.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_19.addWidget(self.comboBox_7)
        self.verticalLayout_19.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_20.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_20.setSpacing(2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_8 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_20.addWidget(self.label_8)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setAutoFillBackground(False)
        self.comboBox_8.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_8.setObjectName("comboBox_8")
        self.verticalLayout_20.addWidget(self.comboBox_8)
        self.verticalLayout_20.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_20)
        self.widget_26 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_31.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_31.setSpacing(2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_19 = QtWidgets.QLabel(self.widget_26)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_31.addWidget(self.label_19)
        self.comboBox_19 = QtWidgets.QComboBox(self.widget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_19.sizePolicy().hasHeightForWidth())
        self.comboBox_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setAutoFillBackground(False)
        self.comboBox_19.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_19.setObjectName("comboBox_19")
        self.verticalLayout_31.addWidget(self.comboBox_19)
        self.verticalLayout_31.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_26)
        self.widget_21 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_26.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_26.setSpacing(2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_14 = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_26.addWidget(self.label_14)
        self.comboBox_14 = QtWidgets.QComboBox(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_14.sizePolicy().hasHeightForWidth())
        self.comboBox_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setAutoFillBackground(False)
        self.comboBox_14.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_14.setObjectName("comboBox_14")
        self.verticalLayout_26.addWidget(self.comboBox_14)
        self.verticalLayout_26.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_27.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_27.setSpacing(2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_15 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_27.addWidget(self.label_15)
        self.comboBox_15 = QtWidgets.QComboBox(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_15.sizePolicy().hasHeightForWidth())
        self.comboBox_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setAutoFillBackground(False)
        self.comboBox_15.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_15.setObjectName("comboBox_15")
        self.verticalLayout_27.addWidget(self.comboBox_15)
        self.verticalLayout_27.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_28.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_28.setSpacing(2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_16 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_28.addWidget(self.label_16)
        self.comboBox_16 = QtWidgets.QComboBox(self.widget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_16.sizePolicy().hasHeightForWidth())
        self.comboBox_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setAutoFillBackground(False)
        self.comboBox_16.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_16.setObjectName("comboBox_16")
        self.verticalLayout_28.addWidget(self.comboBox_16)
        self.verticalLayout_28.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_23)
        self.widget_25 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_30.setContentsMargins(4, 4, 4, 8)
        self.verticalLayout_30.setSpacing(2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_18 = QtWidgets.QLabel(self.widget_25)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_30.addWidget(self.label_18)
        self.comboBox_18 = QtWidgets.QComboBox(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_18.sizePolicy().hasHeightForWidth())
        self.comboBox_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.comboBox_18.setFont(font)
        self.comboBox_18.setAutoFillBackground(False)
        self.comboBox_18.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:26;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.comboBox_18.setObjectName("comboBox_18")
        self.verticalLayout_30.addWidget(self.comboBox_18)
        self.verticalLayout_30.setStretch(1, 8)
        self.verticalLayout_16.addWidget(self.widget_25)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 3)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.tabWidget.addTab(self.Tool, "")
        self.Query = QtWidgets.QWidget()
        self.Query.setObjectName("Query")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Query)
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_16 = QtWidgets.QWidget(self.Query)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.widget_16)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:63;\n"
"height:29;\n"
"font: 9.5pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_12.addWidget(self.pushButton_9)
        self.listWidget_4 = QtWidgets.QListWidget(self.frame)
        self.listWidget_4.setStyleSheet("QListWidget{\n"
"    border-style:none;\n"
"    color:white;\n"
"}\n"
"QListWidget::item:selected{\n"
"background-color: rgb(85, 85, 255);\n"
"}")
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_12.addWidget(self.listWidget_4)
        self.horizontalLayout_8.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_16)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);\n"
"font: 10pt \"Calibri\";\n"
"border-style: none;\n"
"}\n"
"QTextEdit:focus{\n"
"border-style:outset;\n"
"border-width:0.5px;\n"
"border-color: rgb(255, 170, 0);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_9.addWidget(self.textEdit)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 9)
        self.verticalLayout_13.addWidget(self.widget_16)
        self.tabWidget.addTab(self.Query, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.History)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableWidget = QtWidgets.QTableWidget(self.History)
        self.tableWidget.setStyleSheet("QTableView{\n"
"background-color: rgb(55, 55, 64);\n"
"color: white;\n"
"font: 10pt \"Calibri\";\n"
"}\n"
"QHeaderView::section { \n"
"background-color:rgb(61, 155, 229);\n"
"color:white;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout_15.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.History, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_10 = QtWidgets.QWidget(self.tab)
        self.widget_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 55, 64);")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:40;\n"
"height:30;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/external-link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:40;\n"
"height:30;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:40;\n"
"height:30;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:60;\n"
"height:30;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(59, 59, 59, 255), stop:0.328358 rgba(60, 60, 60, 255), stop:0.517413 rgba(68, 68, 68, 255), stop:0.716418 rgba(80, 80, 80, 255), stop:1 rgba(115, 115, 115, 255));\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"width:40;\n"
"height:30;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0248756 rgba(115, 115, 115, 255), stop:0.353234 rgba(80, 80, 80, 255), stop:0.547264 rgba(68, 68, 68, 255), stop:0.781095 rgba(60, 60, 60, 255), stop:1 rgba(59, 59, 59, 255));\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(255, 75, 75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(253, 204, 96);\n"
"}")
        self.pushButton_4.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/whiteIcons/featherwhite/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon8)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 5)
        self.horizontalLayout_6.setStretch(4, 1)
        self.horizontalLayout_6.setStretch(5, 1)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_10)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableView = QtWidgets.QTableView(self.widget_12)
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.verticalLayout_8.addWidget(self.tableView)
        self.verticalLayout_7.addWidget(self.widget_12)
        self.verticalLayout_6.addWidget(self.widget_10)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.widget_9)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_13 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(2)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("height: 8px;\n"
"color:white;")
        self.progressBar.setProperty("value", 10)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.horizontalLayout_7.setStretch(0, 7)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_8.clicked.connect(self.widget_3.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open/Close SideBar</p></body></html>"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Run SQL</p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save SQL</p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Import SQL</p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Aggregate"))
        self.DBLabel.setText(_translate("MainWindow", ".        ."))
        self.SchemaLabel.setText(_translate("MainWindow", ".        ."))
        self.TableLabel.setText(_translate("MainWindow", ".        ."))
        self.TopRowsLabel.setText(_translate("MainWindow", " Limit:"))
        self.TopRowsLineEdit.setText(_translate("MainWindow", "10000"))
        self.NullAsLabel.setText(_translate("MainWindow", " Null As"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Table / Utilities"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Saved SQLs"))
        self.label_2.setText(_translate("MainWindow", "Select"))
        self.label_3.setText(_translate("MainWindow", "Where"))
        self.label_5.setText(_translate("MainWindow", "APPROVE_DECLINE_IND"))
        self.label_6.setText(_translate("MainWindow", "CORP-ID"))
        self.label_7.setText(_translate("MainWindow", "INDUSTRY"))
        self.label_8.setText(_translate("MainWindow", "MCC Code"))
        self.label_19.setText(_translate("MainWindow", "Wallet Type"))
        self.label_14.setText(_translate("MainWindow", "CP_CNP_IND"))
        self.label_15.setText(_translate("MainWindow", "MIT"))
        self.label_16.setText(_translate("MainWindow", "BOPIS Indicator"))
        self.label_18.setText(_translate("MainWindow", "PB Indicator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tool), _translate("MainWindow", "Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Query), _translate("MainWindow", "Query"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SQL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Pop-Out</span></p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">SQL</span></p></body></html>"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Export</span></p></body></html>"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Close Tab</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Result 1"))
        self.label.setText(_translate("MainWindow", "Status Label"))
import resource_rc
