# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 502)
        MainWindow.setStyleSheet("background-color: rgb(42, 38, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setStyleSheet("background-color: rgb(42, 38, 62);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(42, 38, 62);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SelectDateButton = QtWidgets.QPushButton(self.widget)
        self.SelectDateButton.setStyleSheet("QPushButton{\n"
"    /*background-image: url(:/whiteIcons/featherwhite/calendar.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;*/\n"
"    background-color:rgb(99, 89, 145);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    width:100;\n"
"    height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.SelectDateButton.setObjectName("SelectDateButton")
        self.gridLayout.addWidget(self.SelectDateButton, 4, 1, 1, 1)
        self.NRIDLineEdit = QtWidgets.QLineEdit(self.widget)
        self.NRIDLineEdit.setEnabled(False)
        self.NRIDLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.NRIDLineEdit.setObjectName("NRIDLineEdit")
        self.gridLayout.addWidget(self.NRIDLineEdit, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, 2, 20, 11)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.DownloadButton = QtWidgets.QPushButton(self.widget)
        self.DownloadButton.setEnabled(False)
        self.DownloadButton.setBaseSize(QtCore.QSize(100, 40))
        self.DownloadButton.setStyleSheet("QPushButton{\n"
"    /*background-image: url(:/whiteIcons/featherwhite/calendar.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;*/\n"
"    background-color:rgb(99, 89, 145);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    width:100;\n"
"    height:40;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.DownloadButton.setObjectName("DownloadButton")
        self.horizontalLayout.addWidget(self.DownloadButton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 3)
        self.SelectDateLabel = QtWidgets.QLabel(self.widget)
        self.SelectDateLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.SelectDateLabel.setObjectName("SelectDateLabel")
        self.gridLayout.addWidget(self.SelectDateLabel, 3, 1, 1, 1)
        self.MerchantNumberLabel = QtWidgets.QLabel(self.widget)
        self.MerchantNumberLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.MerchantNumberLabel.setObjectName("MerchantNumberLabel")
        self.gridLayout.addWidget(self.MerchantNumberLabel, 0, 1, 1, 1)
        self.NRIDLabel = QtWidgets.QLabel(self.widget)
        self.NRIDLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.NRIDLabel.setObjectName("NRIDLabel")
        self.gridLayout.addWidget(self.NRIDLabel, 0, 0, 1, 1)
        self.MerchantNameLabel = QtWidgets.QLabel(self.widget)
        self.MerchantNameLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.MerchantNameLabel.setObjectName("MerchantNameLabel")
        self.gridLayout.addWidget(self.MerchantNameLabel, 0, 2, 1, 1)
        self.AuthorizationSelectioRadioButton = QtWidgets.QRadioButton(self.widget)
        self.AuthorizationSelectioRadioButton.setStyleSheet("QRadioButton{\n"
"    background-color:rgb(99, 89, 145);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"    height:30;\n"
"    }")
        self.AuthorizationSelectioRadioButton.setObjectName("AuthorizationSelectioRadioButton")
        self.gridLayout.addWidget(self.AuthorizationSelectioRadioButton, 6, 0, 1, 1)
        self.SettlementSelectioRadioButton = QtWidgets.QRadioButton(self.widget)
        self.SettlementSelectioRadioButton.setStyleSheet("QRadioButton{\n"
"    background-color:rgb(99, 89, 145);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"    height:30;\n"
"    }")
        self.SettlementSelectioRadioButton.setObjectName("SettlementSelectioRadioButton")
        self.gridLayout.addWidget(self.SettlementSelectioRadioButton, 6, 1, 1, 1)
        self.RegistrationSelectioRadioButton = QtWidgets.QRadioButton(self.widget)
        self.RegistrationSelectioRadioButton.setEnabled(False)
        self.RegistrationSelectioRadioButton.setStyleSheet("QRadioButton{\n"
"    background-color:rgb(99, 89, 145);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"    height:30;\n"
"    }")
        self.RegistrationSelectioRadioButton.setObjectName("RegistrationSelectioRadioButton")
        self.gridLayout.addWidget(self.RegistrationSelectioRadioButton, 6, 2, 1, 1)
        self.SelectAreaLabel = QtWidgets.QLabel(self.widget)
        self.SelectAreaLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.SelectAreaLabel.setObjectName("SelectAreaLabel")
        self.gridLayout.addWidget(self.SelectAreaLabel, 5, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setEnabled(False)
        self.tableView.setStyleSheet("QTableView {\n"
"    background-color: rgb(53, 50, 76);\n"
"    alternate-background-color: rgb(53, 50, 76);\n"
"    border-style:none;\n"
"    border-radius: 15px;\n"
"    gridline-style:none;\n"
"    \n"
"    }\n"
"\n"
"QTableView::item {\n"
"    background-color: rgb(53, 50, 76);\n"
"    padding: 5px;\n"
"    color:white;\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    }\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: rgb(99, 89, 145);\n"
"    padding: 5px;\n"
"    color:white;\n"
"    }\n"
"\n"
"QHeaderView::section { \n"
"    background-color:rgb(64, 58, 95);\n"
"    alternate-background-color: rgb(64, 58, 95);\n"
"    color:white;\n"
"    }")
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 8, 0, 1, 3)
        self.MerchantNameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.MerchantNameLineEdit.setEnabled(False)
        self.MerchantNameLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.MerchantNameLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.MerchantNameLineEdit.setObjectName("MerchantNameLineEdit")
        self.gridLayout.addWidget(self.MerchantNameLineEdit, 1, 2, 1, 1)
        self.MerchantNumberLineEdit = QtWidgets.QLineEdit(self.widget)
        self.MerchantNumberLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.MerchantNumberLineEdit.setObjectName("MerchantNumberLineEdit")
        self.gridLayout.addWidget(self.MerchantNumberLineEdit, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectDateButton.setText(_translate("MainWindow", "Select Date"))
        self.NRIDLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter NRID</p></body></html>"))
        self.DownloadButton.setText(_translate("MainWindow", "Download"))
        self.SelectDateLabel.setText(_translate("MainWindow", "Select Date"))
        self.MerchantNumberLabel.setText(_translate("MainWindow", "Merchant Number"))
        self.NRIDLabel.setText(_translate("MainWindow", "NRID"))
        self.MerchantNameLabel.setText(_translate("MainWindow", "Merchant Name"))
        self.AuthorizationSelectioRadioButton.setText(_translate("MainWindow", "Authorization"))
        self.SettlementSelectioRadioButton.setText(_translate("MainWindow", "Settlement"))
        self.RegistrationSelectioRadioButton.setText(_translate("MainWindow", "Registration"))
        self.SelectAreaLabel.setText(_translate("MainWindow", "Select Area"))
